### ISSUE TITLE
Merge ipywidget state metadata into final notebook

### ISSUE THREAD

**Issue by akhmerov** [ExecutableBookProject/jupyter-cache#2]
ipywidgets share their state across multiple cells by only outputting the widget view object in each cell, and storing all the information in a global widget state object, that is not associated with any cell, and is optionally added to the notebook metadata. In jupyter-sphinx we extract the widget state [over here](https://github.com/jupyter/jupyter-sphinx/blob/master/jupyter_sphinx/execute.py#L703-L709).

**Comment by chrisjsewell** [comment]
The key for this metadata should be added to `merge_match_into_notebook` here: https://github.com/ExecutableBookProject/jupyter-cache/blob/1b19c7530033447498deb0912fa63d5c0af6f354/jupyter_cache/cache/main.py#L332

and here: https://github.com/ExecutableBookProject/jupyter-cache/blob/1b19c7530033447498deb0912fa63d5c0af6f354/jupyter_cache/base.py#L178
