### ISSUE TITLE
Make `jupyter_cache.cache.main import JupyterCacheBase` more accessible

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/jupyter-cache#29]
> I assume the main usage point is from `jupyter_cache.cache.main import JupyterCacheBase`?

👍 (I should probably make this less deep into the package, but I recall there may be an issue to overcome with cyclic dependency)

_Originally posted by @chrisjsewell in https://github.com/ExecutableBookProject/jupyter-cache/issues/16#issuecomment-596263654_

**Comment by chrisjsewell** [comment]
Note there is already the `get_cache` method, so the issue might not be necessary?

https://github.com/ExecutableBookProject/jupyter-cache/blob/9a43e299be84ea48733bdaa39a4a733609a722a0/jupyter_cache/cli/utils.py#L12

mentioned in https://github.com/ExecutableBookProject/jupyter-cache/issues/16#issuecomment-596379157

**Comment by choldgraf** [comment]
I think either one is fine, but whichever one we recommend should be more clearly documented and discoverable 👍
