### ISSUE TITLE
Document how to deal with expected errors

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/jupyter-cache#30]
It is common in documentation to have notebooks with *expected* errors in them. How should we handle this use-case?

**Comment by chrisjsewell** [comment]
With the `raises-exception` cell tag https://github.com/jupyter/nbclient/blob/507876fa03a71d2461e273ba4d9ec12d3a9ea881/nbclient/client.py#L543

**Comment by chrisjsewell** [comment]
fixed in 40dc3fa73061f4035a5a4c7702c526fdee30ce63 and 7c30e6c623334f089d9697dd944c77d121c8c547 (see https://jupyter-cache.readthedocs.io/en/latest/using/api.html#execution)
