### ISSUE TITLE
Discuss how to visualise historical cache records

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/jupyter-cache#32]
In #16 I mentioned that it was a bit dis-orienting to see multiple versions of the same notebook in the cache list. This is an issue to discuss how that should be handled.

One option would be to include some kind of "Origin URI" value, to make it clear that the cache entries are pointing to the same file.

I'd actually lean towards trying to find a way to *only* show a single entry for a given notebook with the default `list`. It seems that the use-case where somebody wants to list the historical cache records of a notebook to grab one from history from the CLI would be relatively rare. To avoid this confusion, perhaps `jcache cache list` could have a flag like `--include-history` that would include historical cached items, and if not given, the cache would only show the *latest* version of each item.

**Comment by chrisjsewell** [comment]
> only show the latest version of each item

This can be implemented,

An edge case to note is that the *latest* version wouldn't necessarily relate to the most up-to-date for a file, if switching between git branches.

**Comment by chrisjsewell** [comment]
Feel free to reopen if you don't think this fixes the issue
