### ISSUE TITLE
get_cache_record function giving back the staged record

### ISSUE THREAD

**Issue by AakashGfude** [ExecutableBookProject/jupyter-cache#41]
`Get Cache Record` function of `NbCacheBase` gives back the staged record instead of cached.

**To Reproduce**
```
from jupyter_cache.cache.db import NbCacheRecord
from jupyter_cache import get_cache

cache_base = get_cache(path_cache)
cache_list = NbCacheRecord.records_from_uri(file_path, db)
if len(cache_list):
    latest = None
    for item in cache_list:
         if latest is None or (latest < item.created):
            latest = item.created
            latest_pk = item.pk
     cache_record = cache_base.get_cache_record(latest_pk)
```

Here, the cache_record variable contains the staging record instead.

**Screenshot**

![image](https://user-images.githubusercontent.com/6542997/77315701-1b42c180-6d5c-11ea-9450-63bbca430c03.png)

**Environment:**
 - Python Version [3.6.10]
 - Package Version [0.1.0]

**Comment by chrisjsewell** [comment]
It would be ideal if you could provide a PR with a failing unit test, because from a first glance I can’t see where the problem would lie

**Comment by AakashGfude** [comment]
Not able to reproduce today. Yes, the code looks on point. I will reopen this issue, once I face this again and have exact reproducible steps, and a failing unit test.
