### ISSUE TITLE
Version of dependency myst-nb

### ISSUE THREAD

**Issue by AakashGfude** [ExecutableBookProject/jupyter-cache#42]
Is it safe to increment the myst-nb version here to the latest one?

![image](https://user-images.githubusercontent.com/6542997/78416021-62d91f80-7671-11ea-847a-22aeb2dcfcb0.png)

Installing it in development mode uninstalls the latest versions of your other packages as well.

**Comment by chrisjsewell** [comment]
Well just make a PR and see if the docs build on CircleCI 😁

**Comment by AakashGfude** [comment]
@chrisjsewell cool. just wanted a go from you lol.

**Comment by AakashGfude** [comment]
closes https://github.com/ExecutableBookProject/jupyter-cache/pull/45

**Comment by chrisjsewell** [comment]
closed in #46
