### ISSUE TITLE
Use nbclient for execution (when out of alpha)

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/jupyter-cache#5]
Hey all - a quick note that the nbconvert project recently decided to factor out the notebook execution functionality into a separate repository:

https://github.com/jupyter/nbclient

I'm not sure whether this is going to be relevant for this project, given the discussion around *not* using Jupyter Notebooks as the execution layer for code. However, it might be worth watching and potentially contributing upstream to that project, if there are in-scope things that would be beneficial for a repository that is focused on execution etc

**Comment by chrisjsewell** [comment]
closed in d618168e3ce33682528ba5119c7d633e5903f82e
